[project]
name = 'BridgeChain-Infrastructure-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.bridge-structural-registry]
path = 'contracts/bridge-structural-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.safety-monitoring-system]
path = 'contracts/safety-monitoring-system.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
